name: Mirror to Gitea
on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Remove old repo folder
        run: rm -rf repo

      - name: Clone repo as mirror
        run: git clone --mirror https://github.com/Hobbabobba/keyserver.git repo

      - name: Push to Gitea
        env:
          GITEA_USER: ${{ secrets.GITEA_USER }}
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
        run: |
          cd repo
          git remote set-url origin https://${GITEA_USER}:${GITEA_TOKEN}@git.nauheimtech.de/StefanMewes/keyserver.git
          git push --mirror
