name: Mirror to Gitea

on:
  push:
    branches:
      - main   # oder alle Branches, wenn du ALLES spiegeln willst

jobs:
  mirror:
    # läuft nur im Quell-Repo Hobbabobba/keyserver
    if: github.repository == 'Hobbabobba/keyserver'
    runs-on: ubuntu-latest

    steps:
      - name: Clone GitHub repo as bare
        run: |
          rm -rf repo
          git clone --bare https://github.com/Hobbabobba/keyserver.git repo

      - name: Push all branches and tags to Gitea
        env:
          GITEA_USER: ${{ secrets.GITEA_USER }}
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
        run: |
          cd repo
          git remote add gitea https://${GITEA_USER}:${GITEA_TOKEN}@git.nauheimtech.de/StefanMewes/keyserver.git
          git push gitea --all --force
          git push gitea --tags --force
