name: Mirror to Gitea

on: [push]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Push to Gitea
        run: |
          git remote add gitea https://{{ secrets.GITEA_USER }}:${{ secrets.GITEA_TOKEN }}@git.nauheimtech.de/StefanMewes/keyserver.git
          git push --mirror gitea
